export const NL = {
  appName: 'TaakMaatje',
  appTagline: 'Stap voor stap jouw dag',
  splashFooter: 'TaakMaatje — samen sterk',

  enterPin: 'Vul jouw pincode in',
  pinWrong: 'Verkeerde pincode. Probeer het opnieuw!',
  pinHello: 'Hallo. Vul je pincode in.',
  goIn: 'Naar binnen',

  whatToDo: 'Wat wil je doen?',
  tapATask: 'Kies een taak om te starten.',
  tapToSpeak: 'Tik om te spreken',
  listening: 'Luisteren… zeg een taaknaam',
  switchUser: 'Uitloggen',
  overwhelmedBtn: 'Vol hoofd',
  helpBtn: 'Hulp',
  todayStatus: 'Vandaag',
  doneToday: (n) => `Je hebt vandaag ${n} taak${n === 1 ? '' : 'en'} afgerond`,

  progressLabel: (done, total) => `${done} van ${total} stappen klaar`,
  doThisNow: 'Begin hier',
  voiceHint: 'Gebruik je stem',
  voiceListening: 'Luisteren… zeg "klaar", "herhaal" of "pauze"',
  breakNeeded: 'Even pauzeren?',
  startBreak: 'Start pauze',
  stopBreak: 'Stop pauze',
  resetWarning: 'Taak reset na 20 minuten inactiviteit.',
  taskResetMsg: 'De taak is opnieuw begonnen omdat je even weg was.',
  markDone: 'Klaar',
  stepNow: (index, total) => `Stap ${index} van ${total}`,
  timerTitle: 'Timer',
  timerSub: 'Deze stap loopt vanzelf af',
  nextStepCard: 'Volgende stap',
  nextButton: 'Volgende →',
  closeCard: 'Sluiten',
  doneAlready: 'Al gedaan',

  celebrateTitle: 'Goed gedaan!',
  celebrateSub: (task) => `Je hebt "${task}" afgerond.`,
  backToTasks: 'Terug naar taken',
  backToKiosk: 'Terug naar overzicht',

  overwhelmedTitle: 'Vol hoofd?',
  overwhelmedSub: 'Dat is oké. Kies iets dat helpt.',
  overwhelmedBack: 'Ik voel me beter',

  helpSent: 'Je begeleider is op de hoogte gebracht.',
  helpTitle: 'Begeleiding nodig',
  helpMsg: 'Jouw begeleider krijgt nu een bericht.',
  helpConfirm: 'Stuur bericht',
  helpCancel: 'Annuleren',

  howDoYouFeel: 'Hoe voel jij je?',
  moodSub: 'Tik hoe je je voelt.',
  backToTasksBtn: 'Terug naar taken',
  moodResponses: {
    Geweldig: { emoji: '😄', text: 'Dat klinkt goed. Fijn dat het goed gaat.' },
    Goed: { emoji: '🙂', text: 'Goed is mooi. Ga zo rustig verder.' },
    Moe: { emoji: '😴', text: 'Misschien helpt een korte pauze.' },
    Zenuwachtig: { emoji: '😟', text: 'Adem rustig in en uit. Je bent veilig.' },
    Verdrietig: { emoji: '😢', text: 'Het is oké om je zo te voelen.' },
  },

  streakTitle: 'Jouw boom',
  streakSteps: (n) => `${n} stap${n === 1 ? '' : 'pen'} vandaag`,
  streakEncourage: ['Goed bezig', 'Rustig doorgaan', 'Je bent lekker bezig', 'Mooie voortgang'],

  goalTitle: 'Mijn doel',
  goalEmptyTitle: 'Nog geen doel',
  goalEmptySub: 'Je begeleider kan hier een doel voor je klaarzetten.',
  goalProgress: (done, total) => `${done} van ${total} stappen`,

  pointsTitle: 'Punten',
  pointsLabel: 'punten',
  redeem: 'Inwisselen',
  noRewards: 'Nog geen beloningen beschikbaar.',

  chatTitle: 'Chat met begeleiding',
  chatIntro: (name) => `Stuur een bericht naar ${name}.`,
  chatEmpty: 'Nog geen berichten.',
  chatPlaceholder: 'Typ een bericht…',
  send: 'Verstuur',

  medReminderTitle: 'Tijd voor medicijnen',
  medReminderSub: 'Vergeet je medicijnen niet.',
  medReminderDone: 'Ik heb ze genomen',
  medReminderSnooze: 'Herinner me later',

  voiceCmdDone: ['klaar', 'volgende', 'gedaan', 'afgevinkt'],
  voiceCmdBack: ['terug', 'beginscherm', 'home'],
  voiceCmdRepeat: ['herhaal', 'opnieuw', 'nogmaals'],
  voiceCmdBreak: ['pauze', 'rust'],
  voiceGreet: (name) => `Hoi ${name}. Wat wil je vandaag doen?`,
  voiceStartTask: (label) => `We gaan ${label} doen.`,
  voiceNextStep: (n, text) => `Stap ${n}, ${text}`,
  voiceAllDone: (task) => `Goed gedaan. Je hebt ${task} afgerond.`,
  voiceGoHome: 'Terug naar het beginscherm',
  voiceNotUnderstood: 'Ik verstond dat niet. Kies een taak.',
  voiceBreakStart: 'Pauze gestart.',
  voiceWelcome: (name) => `Welkom ${name}.`,
  breakDone: 'De pauze is voorbij.',

  caregiverTitle: 'Begeleider',
  signIn: 'Inloggen',
  register: 'Registreren',
  yourName: 'Jouw naam',
  email: 'E-mailadres',
  password: 'Wachtwoord',
  pleaseWait: 'Even wachten…',
  noAccount: 'Nog geen account? Registreer',
  haveAccount: 'Al een account? Inloggen',
  signOut: 'Uitloggen',

  tileClients: 'Cliënten',
  tileTasks: 'Taken',
  tileGoals: 'Doelen',
  tileRewards: 'Beloningen',
  tileChat: 'Chat',
  tileSettings: 'Instellingen',
  tileMed: 'Medicijnen',
  tileOverwhelm: 'Vol hoofd',
  tileDuty: 'Op dienst',
  dutyTitle: 'Begeleider op dienst',
  dutyIntro: 'Wie is er vandaag aan de beurt? Stel hier in welke begeleider als eerste reageert op meldingen.',
  dutyOnDuty: 'Op dienst',
  dutyEmpty: 'Niemand ingedeeld',
  dutyTakeOver: 'Neem dienst over',
  dutyRelease: 'Geef dienst vrij',
  medManageTitle: 'Medicijnherinneringen',
  medManageIntro: 'Stel vaste momenten in waarop de cliënt een herinnering krijgt.',
  overwhelmManageTitle: 'Vol hoofd activiteiten',
  overwhelmManageIntro: 'Beheer hier de rustgevende activiteiten en bekijk hoe vaak de cliënt deze knop gebruikt.',
  overwhelmStatsTitle: 'Gebruik laatste 7 dagen',
  overwhelmCountToday: 'Vandaag',
  overwhelmCountWeek: '7 dagen',
  overwhelmNoData: 'Nog geen meldingen geregistreerd',
  recordVoice: 'Inspreken',
  recordingVoice: 'Aan het luisteren…',
  voiceNotSupported: 'Spraak werkt niet in deze browser',
  rewardEarned: 'Behaald',
  rewardLocked: 'Nog {n} punten',
  rewardProgress: 'Voortgang',

  addClient: '+ Nieuwe cliënt',
  newClient: 'Nieuwe cliënt',
  clientName: 'Naam',
  colour: 'Kleur',
  pinLabel: 'Pincode (4 cijfers)',
  pinPH: '1234',
  notes: 'Aantekeningen',
  notesPH: 'Opmerkingen…',
  saveClient: 'Opslaan',
  cancel: 'Annuleren',
  clientAdded: 'Cliënt toegevoegd',
  clientSaved: 'Opgeslagen',
  removeClient: 'Verwijder',
  confirmRemove: 'Deze cliënt verwijderen?',
  viewStats: 'Voortgang',
  pinProtected: 'Pincode ingesteld',
  kioskLink: 'Kiosk-link genereren',
  interfaceMode: 'Interface-modus',
  interfaceStandard: 'Standaard',
  interfaceAdult: 'Volwassen',

  customTasksIntro: 'Maak taken met stappen, tijd en punten.',
  addTask: '+ Nieuwe taak',
  newTask: 'Nieuwe taak',
  taskName: 'Naam',
  taskNamePH: 'Bijv. Boodschappen',
  icon: 'Icoon (emoji)',
  stepsLabel: 'Stappen',
  stepsPH: 'Stap 1\nStap 2\nStap 3',
  tipLabel: 'Aanmoediging',
  tipPH: 'Rustig aan, stap voor stap',
  assignTo: 'Koppel aan cliënt',
  allClients: 'Alle cliënten',
  saveTask: 'Opslaan',
  taskAdded: 'Taak toegevoegd',
  removeTask: 'Verwijder',
  stepsCount: (n) => `${n} stap${n === 1 ? '' : 'pen'}`,
  customTasksFor: (name) => `Taken voor ${name}`,
  noCustomTasks: 'Nog geen eigen taken.',
  errorTaskFields: 'Vul een naam in en minimaal één stap.',
  taskPoints: 'Punten',
  taskPhoto: 'Eigen foto',
  stepMinutes: 'Minuten per stap',

  aiTitle: 'AI Taakenmaker',
  aiSub: 'Beschrijf wat de cliënt moet doen. De AI maakt er een duidelijke taak van.',
  aiPlaceholder: 'Bijv. de cliënt moet zelfstandig klaar worden voor dagbesteding',
  aiGenerate: 'Maak taak aan',
  aiGenerating: 'Bezig…',
  aiUseTask: 'Gebruik deze taak',
  aiTryAgain: 'Opnieuw',
  aiError: 'Er ging iets mis. Probeer opnieuw.',

  progressOf: (name) => `Voortgang van ${name}`,
  today: 'Vandaag',
  thisWeek: 'Deze week',
  allTime: 'Totaal',
  moodThisWeek: 'Stemming deze week',
  dailyActivity: 'Dagelijkse taken',
  recentCompletions: 'Recente afrondingen',
  noneYet: 'Nog geen afrondingen.',
  doneBadge: 'Klaar',

  createGoal: 'Nieuw doel',
  goalName: 'Doelnaam',
  goalDescription: 'Beschrijving',
  horizon: 'Stip op de horizon',
  goalSteps: 'Deelstappen',
  addGoalStep: '+ Deelstap',

  addReward: 'Nieuwe beloning',
  rewardName: 'Beloning',
  pointsNeeded: 'Punten nodig',

  chatWithClient: (name) => `Chat met ${name}`,
  dutyTitle: 'Begeleider van dienst',
  morning: 'Ochtend',
  afternoon: 'Middag',
  evening: 'Avond',

  agendaCompact: 'Compact',
  agendaFull: 'Volledige tijdlijn',
  freeTime: (from, to) => `${from} – ${to} vrij`,
};

export const DEFAULT_TASKS = [
  {
    id: 'ochtend',
    label: 'Ochtend routine',
    shortLabel: 'Opstaan',
    subtitle: 'Begin je dag rustig',
    tip: 'Stap voor stap. Jij kunt dit.',
    points: 1,
    steps: [
      { title: 'Word rustig wakker', duration_minutes: 2 },
      { title: 'Drink een glas water', duration_minutes: 2 },
      { title: 'Ga naar het toilet', duration_minutes: 3 },
      { title: 'Poets je tanden', duration_minutes: 3 },
      { title: 'Trek je kleren aan', duration_minutes: 5 },
    ],
  },
  {
    id: 'opruimen',
    label: 'Kamer opruimen',
    shortLabel: 'Opruimen',
    subtitle: 'Maak je kamer rustig',
    tip: 'Een beetje opruimen is al goed.',
    points: 1,
    steps: [
      { title: 'Doe vieze was in de mand', duration_minutes: 3 },
      { title: 'Gooi afval weg', duration_minutes: 2 },
      { title: 'Leg spullen op hun plek', duration_minutes: 5 },
      { title: 'Maak je bed netjes', duration_minutes: 4 },
    ],
  },
  {
    id: 'douchen',
    label: 'Douchen',
    shortLabel: 'Douchen',
    subtitle: 'Fris en schoon',
    tip: 'Neem rustig de tijd.',
    points: 1,
    steps: [
      { title: 'Pak handdoek en kleren', duration_minutes: 2 },
      { title: 'Zet de douche aan', duration_minutes: 1 },
      { title: 'Was je haar en lichaam', duration_minutes: 8 },
      { title: 'Droog je af', duration_minutes: 3 },
      { title: 'Trek schone kleren aan', duration_minutes: 4 },
    ],
  },
  {
    id: 'eten',
    label: 'Iets eten maken',
    shortLabel: 'Eten',
    subtitle: 'Maak iets lekkers',
    tip: 'Rustig werken helpt.',
    points: 1,
    steps: [
      { title: 'Was je handen', duration_minutes: 1 },
      { title: 'Pak eten en spullen', duration_minutes: 3 },
      { title: 'Maak je eten klaar', duration_minutes: 10 },
      { title: 'Eet rustig op', duration_minutes: 15 },
      { title: 'Ruim de spullen op', duration_minutes: 5 },
    ],
  },
  {
    id: 'medicijnen',
    label: 'Medicijnen nemen',
    shortLabel: 'Medicijnen',
    subtitle: 'Goed voor jezelf zorgen',
    tip: 'Pak rustig wat je nodig hebt.',
    points: 1,
    steps: [
      { title: 'Pak je medicijnen', duration_minutes: 1 },
      { title: 'Pak een glas water', duration_minutes: 1 },
      { title: 'Neem je medicijnen in', duration_minutes: 1 },
      { title: 'Zet alles terug', duration_minutes: 1 },
    ],
  },
  {
    id: 'pauze',
    label: 'Even pauzeren',
    shortLabel: 'Pauze',
    subtitle: 'Rustig opladen',
    tip: 'Rust nemen mag.',
    points: 1,
    steps: [
      { title: 'Stop even met wat je doet', duration_minutes: 1 },
      { title: 'Ga rustig zitten', duration_minutes: 1 },
      { title: 'Adem rustig in en uit', duration_minutes: 5 },
    ],
  },
  {
    id: 'buiten',
    label: 'Naar buiten gaan',
    shortLabel: 'Buiten',
    subtitle: 'Frisse lucht halen',
    tip: 'Ook kort naar buiten is goed.',
    points: 1,
    steps: [
      { title: 'Trek je jas en schoenen aan', duration_minutes: 3 },
      { title: 'Pak je sleutels', duration_minutes: 1 },
      { title: 'Loop een rondje buiten', duration_minutes: 10 },
      { title: 'Kom weer rustig terug', duration_minutes: 3 },
    ],
  },
  {
    id: 'slapen',
    label: 'Naar bed gaan',
    shortLabel: 'Slapen',
    subtitle: 'Rustig afsluiten',
    tip: 'Je dag mag nu afronden.',
    points: 1,
    steps: [
      { title: 'Leg je telefoon weg', duration_minutes: 1 },
      { title: 'Poets je tanden', duration_minutes: 3 },
      { title: 'Trek je pyjama aan', duration_minutes: 3 },
      { title: 'Ga in bed liggen', duration_minutes: 2 },
    ],
  },
  {
    id: 'stemming',
    label: 'Hoe voel ik me?',
    shortLabel: 'Stemming',
    subtitle: 'Even stilstaan bij jezelf',
    tip: '',
    steps: [],
    special: 'stemming',
  },
];
